image: timbru31/java-node

stages:
    - deploy

variables: 
   BUNDLE_SRC: deploy-code.zip # defines the zipfile to upload to s3
   ZIP_NAME: photoprinter-ui.zip

before_script:
  - echo "***************** Start CI/CD *************"

# dependencies:
#   stage: dependencies
#   script:
#     - npm install
#   artifacts:
#     paths:
#     - node_modules/


# cache:
#   paths:
#     - node_modules/

# build:
#   stage: build
#   script:
#     - npm build

deploy-job:
    stage: deploy
    only:
        - master
    except: 
        - triggers
    script: 
        - apt-get update -qq && apt-get install -y -qq unzip zip
        - apt-get install -y python3-distutils
        - curl -O https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip.py
        - npm install -g npm@latest
        - npm install -g @angular/cli
        - ng update @angular/cli @angular/core
        - rm -rf dist *.zip deploy-base
        - unset CI
        - npm cache clean --force
        - ng build --prod
        - mv -f dist deploy-base
        - zip -r $BUNDLE_SRC deploy-base
        - pip install awscli # AWS CLI installation
        - aws s3 cp $BUNDLE_SRC $AWS_S3_LOCATION$ZIP_NAME #upload the zipfile to s3
    cache: 
       key: "ui-$CI_BUILD_NAME-$CI_BUILD_REF_NAME"
       untracked: true 
       paths:
           - dist/

after_script:
  - echo "************* End CI/CD *****************"
