version: 0.0
os: linux
files:
    - source: ./deploy-base/ # assumes deployment code is located here
      destination: /var/www/html
permissions:
    - object: /var/www/html
      owner: ec2-user
      mode: 777
      type:
        - directory

hooks:
    BeforeInstall:
        - location: scripts/before_install.sh
          timeout: 180
          runas: ec2-user
    AfterInstall:
        - location: scripts/after_install.sh
          timeout: 180
          runas: ec2-user